### ISSUE TITLE
Tesla door may fail without power failure

### ISSUE THREAD

**Issue by CloudLing20** [ThijsNameIsTaken/EXILED-LightsOut#1]
If he will disable the Tesla door during the power outage, the Tesla door will also be invalid during the non power outage when the power outage occurs this round.

**Comment by ThijsNameIsTaken** [comment]
Confirmed, working on a fix

**Comment by ThijsNameIsTaken** [comment]
Issue fixed as of v1.0.2, Let me know if you have any more issues
