### ISSUE TITLE
TriggeringTesla event issue

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [ThijsNameIsTaken/EXILED-LightsOut#2]
https://github.com/ThijsNameIsTaken/LightsOut/blob/25f35408f0887edf66f23a780ac3f9e5c1a842b4/LightsOut/Main.cs#L87

seems unnecessary and would cause other plugins to break.

**Comment by ThijsNameIsTaken** [comment]
Looking into it, this fixed a bug where tesla gates would stay disabled even after the lights turned on

**Comment by Misaka-ZeroTwo** [comment]
ah, ok

**Comment by ThijsNameIsTaken** [comment]
Should be fixed in v2.0.0-rc1, reopen if there are any issues
