### ISSUE TITLE
Fix config description

### ISSUE THREAD

**Issue by Kirbyfan1223** [ThijsNameIsTaken/EXILED-LightsOut#4]
There has been an error with the config and its confusing the description as a setting. Lines 6 and 7 need to be commented out. If you comment them out they just reset after the server round ends so the plugin would only be valid for 1 round.

**Comment by ThijsNameIsTaken** [comment]
This is an artifact that remained when merging the NWAPI and EXILED config systems, due to EXILED automatically formatting description texts to comment it out correctly. Working on it

**Comment by ThijsNameIsTaken** [comment]
The NWAPI release has been fixed and reuploaded.
